<?php
/**
 * Created by PhpStorm.
 * User: caoyangmin
 * Date: 2017/3/3
 * Time: 下午5:47
 */

namespace EzBpm\Process\Nodes;


use EzBpm\Exceptions\ProcessDefineException;
use EzBpm\Process\ProcessContext;
use EzBpm\Process\ProcessEngine;
use EzBpm\Process\Traits\NoOutput;
use EzBpm\Process\Traits\SingleInput;
use EzBpm\Utils\Verify;

class EndEvent extends ProcessNode
{
    public function __construct($nodeName){
        parent::__construct($nodeName);
    }

    public function handle(ProcessContext $context, ProcessEngine $engine)
    {
        $engine->triggerEndEvent();
        parent::handle($context, $engine); // TODO: Change the autogenerated stub
    }

    use SingleInput;
    use NoOutput;
}